// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rujuwlrxkeeupfpkpqxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1anV3bHJ4a2VldXBmcGtwcXhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5ODczOTAsImV4cCI6MjA2MTU2MzM5MH0.oG1Jzjq3Z3xKFpu1UE04jTLtxqhA_mavMEllXIxrubM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);